flask_app_name: resource_hub
flask_user: flask
flask_home: /opt/
flask_repo: https://github.com/tonykay/resource_hub.git  
flask_scm_ref: main  
flask_app_lauch_script: /usr/local/bin/launch_resource_hub   


app_yum_packages:
  - autoconf
  - automake
  - git
  - gcc
  - libtool

postgres_rhel7_repo: "https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
postgres_library: python-psycopg2
