- name: Deploy, configure, and populate flask repo and virtualenv
  hosts: app_servers
  become: true
  become_user: cloud-user
  gather_facts: false
  tags:
    - application_servers

  roles:

    - flask
