---
- name: Manage OpenStack Servers
  hosts: workstation-25d5.dynamic.opentlc.com
  gather_facts: false
  become: true

  roles:
  - name: openstack_manage_inmemory_inventory
- import_playbook: provision_app_tier.yml
