---
- name: Manage OpenStack Servers
  hosts: workstation-25d5.dynamic.opentlc.com
  gather_facts: true
  become: true

  roles:

    - osp-servers
    - openstack_manage_inmemory_inventory
    - reboot-servers
...
