---
- name: Create app1 instance
  os_server:
    cloud: openstack
    name: app1
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_groups: apps
    delete_fip: yes
    wait: no
    nics:
      - net-name: int_network
    meta: "group=app_servers,deployment_name=QA"
    userdata: |
      #!/bin/bash
      curl -o /root/.ssh/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
      cat /root/.ssh/openstack.pub >> /home/cloud-user/.ssh/authorized_keys

- name: Create app2 instance
  os_server:
    cloud: openstack
    name: app2
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_groups: apps
    delete_fip: yes
    wait: no
    nics:
      - net-name: int_network
    meta: "group=app_servers,deployment_name=QA"
    userdata: |
      #!/bin/bash
      curl -o /root/.ssh/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
      cat /root/.ssh/openstack.pub >> /home/cloud-user/.ssh/authorized_keys

- name: Create db1 instance
  os_server:
    cloud: openstack
    name: db1
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_groups: db
    delete_fip: yes
    wait: no
    nics:
      - net-name: int_network
    meta: "group=database_servers,deployment_name=QA"
    userdata: |
      #!/bin/bash
      curl -o /root/.ssh/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
      cat /root/.ssh/openstack.pub >> /home/cloud-user/.ssh/authorized_keys

- name: Create frontend instance
  os_server:
    cloud: openstack
    name: frontend
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_groups: frontend
    delete_fip: yes
    wait: no
    nics:
      - net-name: int_network
    meta: "group=load_balancers,deployment_name=QA"
    userdata: |
      #!/bin/bash
      curl -o /root/.ssh/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
      cat /root/.ssh/openstack.pub >> /home/cloud-user/.ssh/authorized_keys

- name: Add floating IP to app1 instance
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: app1
    network: ext_network
    wait: true
    timeout: 200

- name: Add floating IP to app2 instance
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: app2
    network: ext_network
    wait: true
    timeout: 200

- name: Add floating IP to db1 instance
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: db1
    network: ext_network
    wait: true
    timeout: 200

- name: Add floating IP to frontend instance
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: frontend
    network: ext_network
    wait: true
    timeout: 200
